# app/src/main/resources/application.yml
spring:
  application:
    name: tft-nexus-ai
  
  # 프로필별 설정 활성화
  profiles:
    active: local
  
  # .env 파일 import
  config:
    import:
      - optional:file:.env[.properties]
      - db-core.yml
      - client-riot-api.yml


server:
  port: 8080
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

  
  # 데이터베이스 설정 (storage 모듈용)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:


---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: local-dev

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: live