# app/src/test/resources/application-test.yml
spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  
  # 테스트용 H2 DB 설정
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  
  # 테스트용 SQL 초기화
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

# Riot API 설정 (실제 API Key 필요)
riot:
  api:
    key: ${RIOT_API_KEY:RGAPI-a4c6fb04-0bd9-4830-b452-77ebe37a47b4}
    url:
      asia: https://asia.api.riotgames.com

logging:
  level:
    org.springframework.web.client: DEBUG
    org.project: DEBUG
    org.hibernate: DEBUG